name: Link Submodule PRs to PDR PR

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

jobs:
  link-submodule-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PDR repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Collect submodule PR links
        id: collect
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          repo_pdr="tangophi/parent_repo"
          pr_number="${{ github.event.pull_request.number }}"
          links=""

          for sub in sub1 sub2; do
            sha=$(git ls-tree HEAD "$sub" | awk '{print $3}')
            if [ -n "$sha" ]; then
              pr_num=$(gh pr list \
                --repo tangophi/$sub \
                --state open \
                --json number,headSha \
                --jq ".[] | select(.headSha==\"$sha\") | .number" || true)
              if [ -n "$pr_num" ]; then
                pr_url="https://github.com/tangophi/$sub/pull/$pr_num"
                links="$links"$'\n'"Linked $sub PR: $pr_url"
              fi
            fi
          done

          echo "links<<EOF" >> $GITHUB_OUTPUT
          echo "$links" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Update PDR PR body
        if: steps.collect.outputs.links != ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          body=$(gh pr view ${{ github.event.pull_request.number }} --json body --jq '.body')
          new_body="$body"$'\n\n'"${{ steps.collect.outputs.links }}"
          gh pr edit ${{ github.event.pull_request.number }} --body "$new_body"
